SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_fuentes](
	[ID] [int] NOT NULL,
	[nombre_fuente] [nvarchar](150) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tbl_fuentes] ADD  CONSTRAINT [pk_tbl_fuentes_id] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
